Update kusama.json
soramitsu/fearless-utils pull request #264
Opened 2022-04-25 08:29 UTC by ilyasoramitsu

Add Shiden crowdloan 2

2022-04-25 08:56 UTC, SkyForger79 commented on crowdloan/kusama.json
> +    "name": "Shiden",
"name": "Shiden Crowdloan 2"

2022-04-25 08:57 UTC, SkyForger79 requested changes
correct the name

2022-04-25 11:42 UTC, zilenka approved these changes

2022-04-26 10:59 UTC, SkyForger79 approved these changes

2022-04-26 10:59 UTC, merged